// Movies
export const MOVIES_LOADING = 'MOVIES_LOADING'
export const MOVIES_LOAD_SUCCESS = 'MOVIES_LOAD_SUCCESS'
export const MOVIES_LOAD_ERROR = 'MOVIES_LOAD_ERROR'

// Planets
export const PLANETS_LOADING = 'PLANETS_LOADING'
export const PLANETS_LOAD_SUCCESS = 'PLANETS_LOAD_SUCCESS'
export const PLANETS_LOAD_ERROR = 'PLANETS_LOAD_ERROR'

// Search
export const SEARCH_PLANETS = 'SEARCH_PLANETS'

// Errors
export const CONNECTION_ERROR = 'CONNECTION_ERROR'

// Add Movie
export const ADD_MOVIE = 'ADD_MOVIE'

// Add Planet
export const ADD_PLANET = 'ADD_PLANET'
